apiVersion: apps/v1
kind: Deployment
metadata:
  name: instant-search-deployment
  namespace: algolia-dev
spec:
  selector:
    matchLabels:
      run: instant-search
  replicas: 2
  template:
    metadata:
      labels:
        run: instant-search
    spec:
      containers:
      - name: instant-search
        image: ghcr.io/farnir/instant-search-demo:v1.0.2-dev
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            port: 3000
            path: /
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10