apiVersion: v1
kind: Service
metadata:
  name: instant-search-service
  labels:
    run: instant-search
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: NodePort
  selector:
    run: instant-search