apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instant-search
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/farnir/instant-search-demo-terraform.git
    targetRevision: HEAD
    path: manifests/app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true