apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/farnir/instant-search-demo
  name: instant-search
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/farnir/instant-search-demo-terraform.git
    targetRevision: HEAD
    path: manifests/app/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true